SUPABASE_URL=https://ngoavvwkqowamzzwrfxm.supabase.co
SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5nb2F2dndrcW93YW16endyZnhtIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MTQ5MDYzNywiZXhwIjoyMDc3MDY2NjM3fQ.xuhDPB9W2RLNX80ayM-hkoMfkSpopdIxjttqbpC5uWo
