NEXT_PUBLIC_SUPABASE_URL=https://ngoavvwkqowamzzwrfxm.supabase.co
NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5nb2F2dndrcW93YW16endyZnhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE0OTA2MzcsImV4cCI6MjA3NzA2NjYzN30.KQO9_xYn89uZrKIEfBhuUXUGt8TpqIdLCQS86zfL6fE
# When you deploy your own backend API (see Section D):
# NEXT_PUBLIC_API_URL=https://<your-internal-api-domain>
